DROP TABLE IF EXISTS urls;

CREATE TABLE urls(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    created TIMESTAMPT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    original_url TEXT NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0
)